/**
 * OS 29 SUBCRITÉRIOS ATIVOS, como o banco os declara — só para os testes.
 *
 * O módulo da Mesa recebe esta lista de fora, de propósito: ele nunca tem uma
 * segunda cópia da verdade. Os testes precisam de uma, e ela vive aqui — uma,
 * não uma por arquivo de teste. Duas cópias divergiriam em silêncio no dia em
 * que um conceito entrasse ou saísse do Catálogo.
 */
export const SUBCRITERIOS_ATIVOS = [
  "ACESSO_MODALIDADE",
  "ACESSO_LOCAL_DE_ATENDIMENTO",
  "ACESSO_DISPONIBILIDADE",
  "ACESSO_PRAZO_PARA_CONSULTA",
  "CONTINUIDADE_RETORNOS",
  "CONTINUIDADE_CANAIS",
  "CONTINUIDADE_COORDENACAO",
  "CONTINUIDADE_POS_PROCEDIMENTO",
  "CONTINUIDADE_EQUIPE_DE_APOIO",
  "MODELO_COMUNICACAO",
  "MODELO_DECISAO_COMPARTILHADA",
  "MODELO_ALTERNATIVAS",
  "MODELO_PARTICIPACAO_FAMILIAR",
  "MODELO_PREFERENCIAS_E_RESTRICOES",
  "MODELO_CONDUCAO_DE_NOTICIAS_DIFICEIS",
  "VIABILIDADE_COBERTURA_E_CONVENIO",
  "VIABILIDADE_CUSTO_E_PAGAMENTO",
  "FORMACAO_GRADUACAO",
  "FORMACAO_RESIDENCIA",
  "FORMACAO_ESPECIALIZACAO",
  "FORMACAO_FELLOWSHIP",
  "FORMACAO_COMPLEMENTAR",
  "EXPERIENCIA_TEMPO_DE_PRATICA",
  "EXPERIENCIA_VOLUME_DE_ATUACAO",
  "EXPERIENCIA_NO_TIPO_DE_CASO",
  "PRATICA_LIMITES_DE_ATUACAO",
  "HISTORICO_TRAJETORIA_INSTITUCIONAL",
  "HISTORICO_ATIVIDADE_ACADEMICA",
  "HISTORICO_AREAS_DE_ATUACAO",
] as const;
