import type { OfficialSourceRecord } from "./types";

/**
 * Baseline do piloto ES — Missões 006–008.
 * Cobertura: 88% (relatório) / 100% (escopo discovery).
 * HUMAN_REVIEW: 6/6 · AUTO_PUBLISH: 0/6.
 */
export const OFFICIAL_SOURCE_SEED: OfficialSourceRecord[] = [
  {
    id: "crm-estadual-es",
    nome: "CRM Estadual ES — WebService CFM",
    tipo: "registro-profissional",
    responsavel: "Integrações / Ops",
    status: "homologacao",
    mock: false,
    homologacao: true,
    staging: false,
    producao: false,
    ultimaSincronizacao: null,
    coberturaObtida: 0,
    confiabilidade: 0.92,
    latenciaMs: null,
    connectorIds: ["crm-estadual"],
    categoriasAtendidas: ["Fontes", "RQE", "Especialidade", "Localização"],
    regrasProtocoloImpactadas: ["ELIG-002", "ELIG-003", "FORM-004", "ELIG-010"],
    ganhoCoberturaEstimado: 12,
    reducaoReviewEstimada: 83,
    ganhoAutoPublishEstimado: 50,
    notas: "Adapter real implementado; requer ALICIA_CFM_WS_CHAVE. OFFLINE no último piloto.",
  },
  {
    id: "cfm-portal",
    nome: "CFM — Conselho Federal de Medicina",
    tipo: "registro-profissional",
    responsavel: "Integrações",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:30.914Z",
    coberturaObtida: 11,
    confiabilidade: 0.9,
    latenciaMs: 45,
    connectorIds: ["cfm"],
    categoriasAtendidas: ["Fontes", "RQE", "Especialidade", "Graduação"],
    regrasProtocoloImpactadas: ["ELIG-002", "ELIG-003", "FORM-004", "PUB-002"],
    ganhoCoberturaEstimado: 8,
    reducaoReviewEstimada: 67,
    ganhoAutoPublishEstimado: 33,
    notas: "Mock ativo; API pública limitada — priorizar consolidação via CRM/CFM SOAP.",
  },
  {
    id: "graduacao-mec",
    nome: "Graduação Médica — MEC / e-MEC",
    tipo: "academico",
    responsavel: "Dados Acadêmicos",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:37.959Z",
    coberturaObtida: 22,
    confiabilidade: 0.88,
    latenciaMs: 120,
    connectorIds: ["academic-graduation"],
    categoriasAtendidas: ["Graduação"],
    regrasProtocoloImpactadas: ["FORM-001", "ELIG-010"],
    ganhoCoberturaEstimado: 22,
    reducaoReviewEstimada: 50,
    ganhoAutoPublishEstimado: 33,
    notas: "Maior ganho em Graduação; 36 evidências no piloto; 3 candidatos fora do escopo ainda sem graduação.",
  },
  {
    id: "residencia-cnrm",
    nome: "Residência Médica — CNRM / COREME",
    tipo: "academico",
    responsavel: "Dados Acadêmicos",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:37.959Z",
    coberturaObtida: 22,
    confiabilidade: 0.87,
    latenciaMs: 130,
    connectorIds: ["academic-residency"],
    categoriasAtendidas: ["Residência"],
    regrasProtocoloImpactadas: ["FORM-002", "ELIG-010"],
    ganhoCoberturaEstimado: 22,
    reducaoReviewEstimada: 100,
    ganhoAutoPublishEstimado: 67,
    notas: "FORM-002 é regra bloqueante de HUMAN_REVIEW; maior alavanca para AUTO_PUBLISH Nível B.",
  },
  {
    id: "fellowship-programas",
    nome: "Fellowship — Programas Avançados",
    tipo: "academico",
    responsavel: "Dados Acadêmicos",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:37.959Z",
    coberturaObtida: 11,
    confiabilidade: 0.82,
    latenciaMs: 110,
    connectorIds: ["academic-fellowship"],
    categoriasAtendidas: ["Residência"],
    regrasProtocoloImpactadas: ["ELIG-010"],
    ganhoCoberturaEstimado: 11,
    reducaoReviewEstimada: 33,
    ganhoAutoPublishEstimado: 17,
    notas: "Complementa residência; impacto menor isolado.",
  },
  {
    id: "hospital-corpo-clinico",
    nome: "Hospital — Corpo Clínico (ICOT / Meridional)",
    tipo: "institucional",
    responsavel: "Parcerias Clínicas",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:30.914Z",
    coberturaObtida: 6,
    confiabilidade: 0.84,
    latenciaMs: 180,
    connectorIds: ["hospital"],
    categoriasAtendidas: ["Instituições", "Localização", "Residência"],
    regrasProtocoloImpactadas: ["FORM-003", "ELIG-010"],
    ganhoCoberturaEstimado: 6,
    reducaoReviewEstimada: 50,
    ganhoAutoPublishEstimado: 33,
    notas: "Discovery DEGRADED; crawler/API por hospital necessário.",
  },
  {
    id: "universidade-docente",
    nome: "Universidade — Corpo Docente (EMESCAM / UFES)",
    tipo: "academico",
    responsavel: "Parcerias Acadêmicas",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:30.914Z",
    coberturaObtida: 5,
    confiabilidade: 0.79,
    latenciaMs: 200,
    connectorIds: ["universidade"],
    categoriasAtendidas: ["Graduação", "Residência", "Instituições"],
    regrasProtocoloImpactadas: ["FORM-001", "FORM-002", "ELIG-010"],
    ganhoCoberturaEstimado: 10,
    reducaoReviewEstimada: 50,
    ganhoAutoPublishEstimado: 33,
    notas: "Candidatos fora do escopo (Lucas, André, Helena Martins) dependem desta fonte.",
  },
  {
    id: "sociedade-medica",
    nome: "Sociedade Médica — SBOT / Associações",
    tipo: "sociedade",
    responsavel: "Parcerias Profissionais",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:30.914Z",
    coberturaObtida: 5,
    confiabilidade: 0.82,
    latenciaMs: 95,
    connectorIds: ["sociedade-medica"],
    categoriasAtendidas: ["Especialidade", "RQE", "Residência"],
    regrasProtocoloImpactadas: ["FORM-004", "ELIG-007", "ELIG-010"],
    ganhoCoberturaEstimado: 5,
    reducaoReviewEstimada: 33,
    ganhoAutoPublishEstimado: 17,
    notas: "Confirma especialidade e trajetória; API por sociedade.",
  },
  {
    id: "site-institucional",
    nome: "Site Institucional — Clínicas e Consultórios",
    tipo: "institucional",
    responsavel: "Crawler / Ops",
    status: "mock",
    mock: true,
    homologacao: false,
    staging: false,
    producao: false,
    ultimaSincronizacao: "2026-07-23T04:25:30.914Z",
    coberturaObtida: 5,
    confiabilidade: 0.75,
    latenciaMs: 250,
    connectorIds: ["site-institucional"],
    categoriasAtendidas: ["Instituições", "Localização"],
    regrasProtocoloImpactadas: ["FORM-003", "ELIG-011"],
    ganhoCoberturaEstimado: 4,
    reducaoReviewEstimada: 17,
    ganhoAutoPublishEstimado: 0,
    notas: "Fonte nível 4–5; não desbloqueia AUTO_PUBLISH sozinha.",
  },
];

export function findSourceById(id: string): OfficialSourceRecord | undefined {
  return OFFICIAL_SOURCE_SEED.find((source) => source.id === id);
}

export function findSourceByConnectorId(connectorId: string): OfficialSourceRecord | undefined {
  return OFFICIAL_SOURCE_SEED.find((source) => source.connectorIds.includes(connectorId));
}
