import type { AcademicEvidenceKind, AcademicRawRecord } from "./types";

/** Candidatos alinhados ao piloto ES (discovery). */
export const ACADEMIC_GRADUATION_MOCK: AcademicRawRecord[] = [
  {
    nome: "Dr. Ricardo Almeida",
    crm: "45210",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Vitória",
    estado: "ES",
    institution: "Universidade Federal do Espírito Santo",
    degree: "Medicina",
    startYear: "2002",
    endYear: "2007",
    source: "https://mec.gov.br/mock/graduacao/ricardo-almeida",
    confidence: 0.91,
  },
  {
    nome: "Dra. Fernanda Lopes",
    crm: "38901",
    crm_uf: "ES",
    especialidade: "Neurocirurgia",
    cidade: "Serra",
    estado: "ES",
    institution: "Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória",
    degree: "Medicina",
    startYear: "2004",
    endYear: "2009",
    source: "https://emescam.edu.br/mock/graduacao/fernanda-lopes",
    confidence: 0.89,
  },
  {
    nome: "Dr. Paulo Mendes",
    crm: "51332",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Cariacica",
    estado: "ES",
    institution: "Universidade Vila Velha",
    degree: "Medicina",
    startYear: "2006",
    endYear: "2011",
    source: "https://uvv.br/mock/graduacao/paulo-mendes",
    confidence: 0.87,
  },
  {
    nome: "Dra. Camila Rocha",
    crm: "29887",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Vila Velha",
    estado: "ES",
    institution: "Universidade Federal do Espírito Santo",
    degree: "Medicina",
    startYear: "2000",
    endYear: "2005",
    source: "https://mec.gov.br/mock/graduacao/camila-rocha",
    confidence: 0.88,
  },
  {
    nome: "Dr. Gustavo Neri",
    crm: "33441",
    crm_uf: "ES",
    especialidade: "Neurocirurgia",
    cidade: "Vitória",
    estado: "ES",
    institution: "Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória",
    degree: "Medicina",
    startYear: "2003",
    endYear: "2008",
    source: "https://emescam.edu.br/mock/graduacao/gustavo-neri",
    confidence: 0.86,
  },
  {
    nome: "Dra. Helena Duarte",
    crm: "40118",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Linhares",
    estado: "ES",
    institution: "Universidade Federal do Espírito Santo",
    degree: "Medicina",
    startYear: "2005",
    endYear: "2010",
    source: "https://mec.gov.br/mock/graduacao/helena-duarte",
    confidence: 0.85,
  },
];

export const ACADEMIC_RESIDENCY_MOCK: AcademicRawRecord[] = [
  {
    nome: "Dr. Ricardo Almeida",
    crm: "45210",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Vitória",
    estado: "ES",
    institution: "Instituto de Ortopedia e Traumatologia de Vitória",
    program: "Ortopedia e Traumatologia",
    startYear: "2008",
    endYear: "2010",
    source: "https://icot.org.br/mock/residencia/ricardo-almeida",
    confidence: 0.9,
  },
  {
    nome: "Dra. Fernanda Lopes",
    crm: "38901",
    crm_uf: "ES",
    especialidade: "Neurocirurgia",
    cidade: "Serra",
    estado: "ES",
    institution: "Hospital Estadual Central",
    program: "Neurocirurgia",
    startYear: "2010",
    endYear: "2013",
    source: "https://hec.es.gov.br/mock/residencia/fernanda-lopes",
    confidence: 0.88,
  },
  {
    nome: "Dr. Paulo Mendes",
    crm: "51332",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Cariacica",
    estado: "ES",
    institution: "Instituto de Ortopedia e Traumatologia de Vitória",
    program: "Ortopedia e Traumatologia",
    startYear: "2012",
    endYear: "2014",
    source: "https://icot.org.br/mock/residencia/paulo-mendes",
    confidence: 0.87,
  },
  {
    nome: "Dra. Camila Rocha",
    crm: "29887",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Vila Velha",
    estado: "ES",
    institution: "Instituto de Ortopedia e Traumatologia de Vitória",
    program: "Ortopedia e Traumatologia",
    startYear: "2006",
    endYear: "2008",
    source: "https://icot.org.br/mock/residencia/camila-rocha",
    confidence: 0.89,
  },
  {
    nome: "Dr. Gustavo Neri",
    crm: "33441",
    crm_uf: "ES",
    especialidade: "Neurocirurgia",
    cidade: "Vitória",
    estado: "ES",
    institution: "Hospital Estadual Central",
    program: "Neurocirurgia",
    startYear: "2009",
    endYear: "2012",
    source: "https://hec.es.gov.br/mock/residencia/gustavo-neri",
    confidence: 0.86,
  },
  {
    nome: "Dra. Helena Duarte",
    crm: "40118",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Linhares",
    estado: "ES",
    institution: "Instituto de Ortopedia e Traumatologia de Vitória",
    program: "Ortopedia e Traumatologia",
    startYear: "2011",
    endYear: "2013",
    source: "https://icot.org.br/mock/residencia/helena-duarte",
    confidence: 0.84,
  },
];

export const ACADEMIC_FELLOWSHIP_MOCK: AcademicRawRecord[] = [
  {
    nome: "Dr. Ricardo Almeida",
    crm: "45210",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Vitória",
    estado: "ES",
    institution: "Hospital Israelita Albert Einstein",
    program: "Fellowship em Cirurgia do Joelho",
    startYear: "2011",
    endYear: "2012",
    source: "https://einstein.br/mock/fellowship/ricardo-almeida",
    confidence: 0.83,
  },
  {
    nome: "Dra. Fernanda Lopes",
    crm: "38901",
    crm_uf: "ES",
    especialidade: "Neurocirurgia",
    cidade: "Serra",
    estado: "ES",
    institution: "Hospital Sírio-Libanês",
    program: "Fellowship em Neurocirurgia Vascular",
    startYear: "2014",
    endYear: "2015",
    source: "https://hsl.org.br/mock/fellowship/fernanda-lopes",
    confidence: 0.82,
  },
  {
    nome: "Dr. Paulo Mendes",
    crm: "51332",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Cariacica",
    estado: "ES",
    institution: "Instituto de Ortopedia e Traumatologia de Vitória",
    program: "Fellowship em Cirurgia de Quadril",
    startYear: "2015",
    endYear: "2016",
    source: "https://icot.org.br/mock/fellowship/paulo-mendes",
    confidence: 0.81,
  },
  {
    nome: "Dra. Camila Rocha",
    crm: "29887",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Vila Velha",
    estado: "ES",
    institution: "Hospital Israelita Albert Einstein",
    program: "Fellowship em Cirurgia de Ombro",
    startYear: "2009",
    endYear: "2010",
    source: "https://einstein.br/mock/fellowship/camila-rocha",
    confidence: 0.8,
  },
  {
    nome: "Dr. Gustavo Neri",
    crm: "33441",
    crm_uf: "ES",
    especialidade: "Neurocirurgia",
    cidade: "Vitória",
    estado: "ES",
    institution: "Hospital Sírio-Libanês",
    program: "Fellowship em Neurocirurgia Oncológica",
    startYear: "2013",
    endYear: "2014",
    source: "https://hsl.org.br/mock/fellowship/gustavo-neri",
    confidence: 0.79,
  },
  {
    nome: "Dra. Helena Duarte",
    crm: "40118",
    crm_uf: "ES",
    especialidade: "Ortopedia",
    cidade: "Linhares",
    estado: "ES",
    institution: "Instituto de Ortopedia e Traumatologia de Vitória",
    program: "Fellowship em Ortopedia Pediátrica",
    startYear: "2014",
    endYear: "2015",
    source: "https://icot.org.br/mock/fellowship/helena-duarte",
    confidence: 0.78,
  },
];

export function academicMockByKind(kind: AcademicEvidenceKind): AcademicRawRecord[] {
  switch (kind) {
    case "graduation":
      return ACADEMIC_GRADUATION_MOCK;
    case "residency":
      return ACADEMIC_RESIDENCY_MOCK;
    case "fellowship":
      return ACADEMIC_FELLOWSHIP_MOCK;
  }
}
