export * from "@/alicia/domain/doctor";
export * from "@/alicia/domain/education";
export * from "@/alicia/domain/fellowship";
export * from "@/alicia/domain/institution";
export * from "@/alicia/domain/practice-location";
export * from "@/alicia/domain/residency";
export * from "@/alicia/domain/source";
export * from "@/alicia/domain/specialty";
export * from "@/alicia/domain/verification";
